api:
  tableId-service:
    uri: TableId-service/tableid
  product-service:
    uri: product-service/product
  customer-service:
    uri: customer-service/customer
  movement-account-service:
    uri: movement-account-service/movement-account
server:
  port: '8086'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
#server:
#  port: ${PORT:${SERVER_PORT:0}}      
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}  