server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/account/**
        
      - id: configuration-service
        uri: lb://configuration-service
        predicates:
        - Path=/configuration/**

      - id: credit-service
        uri: lb://credit-service
        predicates:
        - Path=/credit/**

      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**

      - id: holder-account-service
        uri: lb://holder-account-service
        predicates:
        - Path=/holder-account/**

      - id: movement-account-service
        uri: lb://movement-account-service
        predicates:
        - Path=/movement-account/**

      - id: movementCredit-service
        uri: lb://movementCredit-service
        predicates:
        - Path=/movementCredit/**

      - id: product-service
        uri: lb://product-service/
        predicates:
        - Path=/product/**

      - id: SignCustAccount-service
        uri: lb://SignCustAccount-service
        predicates:
        - Path=/signCustAccount/**

      - id: TableId-service
        uri: lb://TableId-service/
        predicates:
        - Path=/tableid/**
      
      - id: reports-account-service
        uri: lb://reports-account-service
        predicates:
        - Path=/reports/**
      
      - id: card-service
        uri: lb://card-service
        predicates:
        - Path=/card/**

      - id: card-service
        uri: lb://card-service/
        predicates:
        - Path=/card/**
        
      - id: bank-transfers-service
        uri: lb://bank-transfers-service/
        predicates:
        - Path=/bank-transfer/**

      
      - id: account-card-service
        uri: lb://account-card-service/
        predicates:
        - Path=/accountcard/**

      - id: movement-card-service
        uri: lb://movement-card-service/
        predicates:
        - Path=/movement-card/**
        
      - id: wallet-service
        uri: lb://wallet-service/
        predicates:
        - Path=/api/v1/wallet/**
        
      - id: movement-wallet-service
        uri: lb://movement-wallet-service/
        predicates:
        - Path=/api/v1/movement-wallet/**
        
      - id: purchase-request-service
        uri: lb://purchase-request-service/
        predicates:
        - Path=/api/v1/purchaserequest/**

      - id: purchase-transaction-service
        uri: lb://purchase-transaction-service/
        predicates:
        - Path=/api/v1/purchasetransaction/**
      
      - id: exchange-rate-service
        uri: lb://exchange-rate-service/
        predicates:
        - Path=/api/v1/exchangerate/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
logging:
  file:
    name: log/${spring.application.name}.log   
  logback:
    rollingpolicy:
      max-file-size: 3MB
      file-name-pattern: log/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 100MB
      clean-history-on-start: true
      max-history: 10
