api:
  tableId-service:
    uri: TableId-service/tableid 
  holder-account-service:
    uri: holder-account-service/holder-account
  SignCustAccount-service:
    uri: SignCustAccount-service/signCustAccount
  account-service:
    uri: account-service/account 
  credit-service:
    uri: credit-service/credit
  movement-card-service:
    uri: movement-card-service/movement-card  
server:
  port: 8094
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
#server:
#  port: ${PORT:${SERVER_PORT:0}}      
feign:
  circuitbreaker:
    enabled: true
  client: 
    config: 
      default: 
        connectTimeout: 10000 
        readTimeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}  