api:
  tableId-service:
    uri: http://localhost:8091/tableid
  product-service:
    uri: http://localhost:8083/product
  customer-service:
    uri: http://localhost:8087/customer
  movementCredit-service:
    uri: http://localhost:8085/movementCredit
server:
  port: '8084'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost