api:
  tableId-service:
    uri: TableId-service/tableid
  account-service:
    uri: account-service/account 
  credit-service:
    uri: credit-service/credit
server:
  port: '8087'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
feign:
  circuitbreaker:
    enabled: true
  client: 
    config: 
      default: 
        connectTimeout: 10000 
        readTimeout: 20000
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost