server:
  port: 9084
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}  
logging:
  file:
    name: log/${spring.application.name}.log   
  logback:
    rollingpolicy:
      max-file-size: 3MB
      file-name-pattern: log/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 100MB
      clean-history-on-start: true
      max-history: 10