api:
  tableId-service:
    uri: TableId-service/tableid
  customer-service:
    uri: customer-service/customer
  account-service:
    uri: account-service/account
server:
  port: '8090'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost