server:
  port: 8085
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
api:
  credit-service:
    uri: http://localhost:8084/credit
  tableId-service:
    uri: http://localhost:8091/tableid
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost