server:
  port: 8085
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
api:
  credit-service:
    uri: http://credit-service:8084/credit
  tableId-service:
    uri: http://TableId-service:8091/tableid
feign:
  circuitbreaker:
    enabled: true
  client: 
    config: 
      default: 
        connectTimeout: 10000 
        readTimeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost