server:
  port: 8083
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
api:
  uri:
    tableId-service: TableId-service/tableid 
