server:
  port: 8083
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
feign:
  circuitbreaker:
    enabled: true
  client: 
    config: 
      default: 
        connectTimeout: 10000 
        readTimeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
api:  
    tableId-service:
      uri: TableId-service/tableid 
    configuration-service:
      uri: configuration-service/configuration 