api:
  tableId-service:
    uri: TableId-service/tableid
  product-service:
    uri: product-service/product
  credit-service:
    uri: credit-service/credit
  account-service:
    uri: account-service/account
  movement-account-service:
    uri: movement-account-service/movement-account
  customer-service:
    uri: customer-service/customer 
  movementCredit-service:
    uri: movementCredit-service/movementCredit 
server:
  port: '8097'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
#server:
#  port: ${PORT:${SERVER_PORT:0}}      
feign:
  circuitbreaker:
    enabled: true
  client: 
    config: 
      default: 
        connectTimeout: 10000 
        readTimeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}  
logging:
  file:
    name: log/${spring.application.name}.log   
  logback:
    rollingpolicy:
      max-file-size: 3MB
      file-name-pattern: log/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 100MB
      clean-history-on-start: true
      max-history: 10