server:
  port: 8089
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
api:
  account-service:
    uri: account-service/account
  product-service: 
    uri: product-service/product
  customer-service:
    uri: customer-service/customer
  tableId-service:
    uri: TableId-service/tableid
